package pandoc

import (
	"context"
	"errors"
	"flag"
	"html/template"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/emad-elsaid/xlog/markdown/ast"

	"github.com/emad-elsaid/xlog"
)

const (
	extODT = ".odt"
	extOrg = ".org"
	extRST = ".rst"
)

var SUPPORTED_EXT = []string{extOrg, extRST, ".rtf", extODT}
var pandoc_support bool

func init() {
	flag.BoolVar(&pandoc_support, "pandoc", false, "Use pandoc to render "+strings.Join(SUPPORTED_EXT, ", "))

	xlog.RegisterExtension(pandoc{})
}

type pandoc struct{}

func (pandoc) Name() string { return "pandoc" }
func (p pandoc) Init() {
	if pandoc_support {
		xlog.RegisterPageSource(&p)
	}
}

func (p *pandoc) Page(name string) xlog.Page {
	for _, ext := range SUPPORTED_EXT {
		pg := page{
			name: name,
			ext:  ext,
		}
		if pg.Exists() {
			return &pg
		}
	}

	return nil
}

func (p *pandoc) Each(ctx context.Context, f func(xlog.Page)) {
	_ = filepath.WalkDir(".", func(name string, d fs.DirEntry, err error) error {
		select {

		case <-ctx.Done():
			return errors.New("context stopped")

		default:
			ext := path.Ext(name)
			basename := name[:len(name)-len(ext)]

			for _, supported_ext := range SUPPORTED_EXT {
				if supported_ext == ext {
					f(&page{
						name: basename,
						ext:  ext,
					})
					break
				}
			}

		}

		return nil
	})
}

type page struct {
	name string
	ext  string
}

func (p *page) Name() string {
	return p.name
}

func (p *page) FileName() string {
	return filepath.FromSlash(p.name) + p.ext
}

func (p *page) Exists() bool {
	_, err := os.Stat(p.FileName())
	return err == nil
}

func (p *page) Render() template.HTML {
	cmd := exec.Command("pandoc", "-f", p.ext[1:], "-t", "html", p.FileName(), "--output", "-") // #nosec G204 -- FileName from trusted page system, ext from registered extensions
	html, err := cmd.Output()
	if err != nil {
		slog.Error("Couldn't parse file to markdown using pandoc", "file", p.FileName(), "error", err)
	}

	// #nosec G203 -- HTML is generated by pandoc, a trusted conversion tool, from user-owned files
	return template.HTML(html)
}

func (p *page) Content() xlog.Markdown {
	dat, err := os.ReadFile(p.FileName())
	if err != nil {
		return ""
	}
	return xlog.Markdown(dat)
}

func (p *page) ModTime() time.Time {
	s, err := os.Stat(p.FileName())
	if err != nil {
		return time.Time{}
	}

	return s.ModTime()
}

func (p *page) Delete() bool {
	defer xlog.Trigger(xlog.PageDeleted, p)

	if p.Exists() {
		err := os.Remove(p.FileName())
		if err != nil {
			slog.Error("Can't delete page", "page", p.Name(), "error", err)
			return false
		}
	}
	return true
}

func (p *page) Write(content xlog.Markdown) bool {
	if xlog.Config.Readonly {
		return false
	}

	defer xlog.Trigger(xlog.PageChanged, p)

	name := p.FileName()
	if err := os.MkdirAll(filepath.Dir(name), 0700); err != nil {
		slog.Error("Failed to create directory", "path", filepath.Dir(name), "error", err)
		return false
	}

	content = xlog.Markdown(strings.ReplaceAll(string(content), "\r\n", "\n"))
	if err := os.WriteFile(name, []byte(content), 0600); err != nil {
		slog.Error("Can't write page", "page", p.Name(), "error", err)
		return false
	}
	return true
}

func (p *page) AST() ([]byte, ast.Node) { return []byte{}, ast.NewDocument() }
