#!/usr/bin/env ruby

require 'json'

bookmarks = File.read(File.expand_path("~/.config/google-chrome/Default/Bookmarks"))
bookmarks = JSON.parse(bookmarks)["roots"]

def render(item)

  if item["type"] == "folder"
    puts "<li>#{item["name"]}"
    puts "<ul>"
    item["children"].each do |child|
      render(child)
    end
    puts "</ul>"
    puts "</li>"
  elsif item["type"] == "url"
    puts "<li><a href='#{item["url"]}'>#{item["name"]}</a></li>"
  end

end

bookmarks.each do |key, value|
  render value
end
