#!/usr/bin/env ruby

keyword = $stdin.read

puts "text/markdown"
Dir['*.md'].each do |file|
  basename = File.basename(file, '.md')
  content = File.read(file)
  match = content.lines.select { |line| line.include?(keyword) }

  unless match.empty?
    puts "# #{basename} (#{match.length} Matches)"
    puts match
  end
end
